services:
  traefik:
    container_name: traefik
    image: traefik:v3.3
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=app
      - --providers.file.directory=/configs
      - --log.level=DEBUG
      - --accesslog=true
      # - --certificatesresolvers.myresolver.acme.email=your-email@example.com  # Replace with your email
      # - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      # - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --entrypoints.websecure.http.tls=true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
      - ./configs:/configs
      # - ./letsencrypt:/letsencrypt
    networks:
      - app

networks:
  app:
    name: app
    driver: bridge
